import './globals.css';
import React from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Razaqisama',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main className="h-screen p-8">
          <div className="h-[100%] flex border-[1px] rounded-xl overflow-hidden">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
